version: "3.9"

volumes:
  postgresql-stage-volume:

services:
  db:
    image: postgres
    container_name: stage_database
    volumes:
      - postgresql-stage-volume:/var/lib/postgresql/data
    expose:
      - "5433"
    command: -p 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5433'

  etaskify-api-swagger-ui:
    hostname: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "7077:8098"
    volumes:
      - "./docs:/usr/share/nginx/html/docs"
    environment:
      - API_URL=/docs/api.yaml
      - VALIDATOR_URL=none
